# Generated by Django 5.2.13 on 2026-04-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("gender_probability", models.FloatField(blank=True, null=True)),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("age_group", models.CharField(blank=True, max_length=50, null=True)),
                ("country_id", models.CharField(blank=True, max_length=10, null=True)),
                ("country_probability", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "profiles",
            },
        ),
    ]
