# Generated by Django 5.2.13 on 2026-04-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.CharField(
                editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
    ]
